### ISSUE TITLE
After upgrade HA to 0.66.1 System Alarm don't start automatically

### ISSUE THREAD

**Issue by vpomax** [runningman84/home-assistant-apps#3]
I'm using HASSIO v. 0.99, after I upgraded HA from v. 0.65.5 to v. 0.66.1 System Alarm do not start automatically.
This is my automation... until v. 0.65.5 it worked fine...

```
  - alias: system alarm HOME automatic on
    trigger:
      platform: time
      hours: 23
      minutes: 30
      seconds: 00
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.samsung_s8_wifi
        state: 'home'
      - condition: state
        entity_id: device_tracker.samsung_s8_bt
        state: 'home'
      - condition: state
        entity_id: device_tracker.huawei_p8_wifi
        state: 'home'
      - condition: state
        entity_id: device_tracker.huawei_p8_bt
        state: 'home'
    action:
      service: alarm_control_panel.alarm_arm_home
      data: {"entity_id":"alarm_control_panel.ha_alarm","code":"12345678"}
```
