### ISSUE TITLE
changes in new alarm.py

### ISSUE THREAD

**Issue by vpomax** [runningman84/home-assistant-apps#9]
Hi Philipp, which changes you have applied to AlarmSystem configuration?
with the new alarm.py system is not armed by input_boolean like this do not works...

```
  - alias: system alarm home on
    trigger:
      platform: state
      entity_id: input_boolean.systemalarm_home
      to: 'on'
    action:
      service: alarm_control_panel.alarm_arm_home
      data: {"entity_id":"alarm_control_panel.ha_alarm","code":"1234"}
```

I saw you changed 
- armed_home_sensors:    to    armed_home_binary_sensors:
- armed_away_sensors:   to    armed_away_binary_sensors:

other changes?
